<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Bank_detail extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Bank_detail_model');
    } 

    /*
     * Listing of bank_details
     */
    function index()
    {
        $data['bank_details'] = $this->Bank_detail_model->get_all_bank_details();
        
        $data['_view'] = 'bank_detail/index';
        $this->load->view('layouts/main',$data);
    }
}
