<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Company extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Company_model');
    } 

    /*
     * Listing of companies
     */
    function index()
    {
        $data['companies'] = $this->Company_model->get_all_companies($_SESSION['company_id']);
        
        $data['_view'] = 'company/index';
        $this->load->view('layouts/main',$data);
    }  

    /*
     * Editing a company
     */
    function edit($company_id)
    {   
        // check if the company exists before trying to edit it
        $data['company'] = $this->Company_model->get_company($company_id);
        
        if(isset($data['company']['company_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'status' => $this->input->post('status'),
					'password' => $this->input->post('password'),
					'rating' => $this->input->post('rating'),
					'type' => $this->input->post('type'),
					'name' => $this->input->post('name'),
					'email' => $this->input->post('email'),
					'phone' => $this->input->post('phone'),
					'enrolled' => $this->input->post('enrolled'),
					'timestamp' => $this->input->post('timestamp'),
					'logo' => $this->input->post('logo'),
					'about' => $this->input->post('about'),
                );

                $this->Company_model->update_company($company_id,$params);            
                redirect('company/index');
            }
            else
            {
                $data['_view'] = 'company/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The company you are trying to edit does not exist.');
    }
}
