<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Like extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Like_model');
    } 

    /*
     * Listing of likes
     */
    function index()
    {
        $data['likes'] = $this->Like_model->get_all_likes();
        
        $data['_view'] = 'like/index';
        $this->load->view('layouts/main',$data);
    }
}
