<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Review extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Review_model');
    } 

    /*
     * Listing of reviews
     */
    function index()
    {
        $data['reviews'] = $this->Review_model->get_all_reviews($_SESSION['company_id']);
        
        $data['_view'] = 'review/index';
        $this->load->view('layouts/main',$data);
    }
}
