<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_company extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_company_model');
    } 

    /*
     * Listing of user_companies
     */
    function index()
    {
        $data['user_companies'] = $this->User_company_model->get_all_user_companies();
        
        $data['_view'] = 'user_company/index';
        $this->load->view('layouts/main',$data);
    }
}
