<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Usernotification extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Usernotification_model');
    } 

    /*
     * Listing of usernotifications
     */
    function index()
    {
        $data['usernotifications'] = $this->Usernotification_model->get_all_usernotifications();
        
        $data['_view'] = 'usernotification/index';
        $this->load->view('layouts/main',$data);
    }
}
