<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Company_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get company by company_id
     */
    function get_company($company_id)
    {
        return $this->db->get_where('companies',array('company_id'=>$company_id))->row_array();
    }
        
    /*
     * Get all companies
     */
    function get_all_companies()
    {
        $this->db->order_by('company_id', 'desc');
        return $this->db->get('companies')->result_array();
    }
        
    /*
     * function to add new company
     */
    function add_company($params)
    {
        $this->db->insert('companies',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update company
     */
    function update_company($company_id,$params)
    {
        $this->db->where('company_id',$company_id);
        return $this->db->update('companies',$params);
    }
    
    /*
     * function to delete company
     */
    function delete_company($company_id)
    {
        return $this->db->delete('companies',array('company_id'=>$company_id));
    }
}
