<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Bank_detail_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get bank_detail by bank_id
     */
    function get_bank_detail($bank_id)
    {
        return $this->db->get_where('bank_details',array('bank_id'=>$bank_id))->row_array();
    }
        
    /*
     * Get all bank_details
     */
    function get_all_bank_details()
    {
        $this->db->order_by('bank_id', 'desc');
        return $this->db->get('bank_details')->result_array();
    }
        
    /*
     * function to add new bank_detail
     */
    function add_bank_detail($params)
    {
        $this->db->insert('bank_details',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update bank_detail
     */
    function update_bank_detail($bank_id,$params)
    {
        $this->db->where('bank_id',$bank_id);
        return $this->db->update('bank_details',$params);
    }
    
    /*
     * function to delete bank_detail
     */
    function delete_bank_detail($bank_id)
    {
        return $this->db->delete('bank_details',array('bank_id'=>$bank_id));
    }
}
