<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Companynotification_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get companynotification by cn_id
     */
    function get_companynotification($cn_id)
    {
        return $this->db->get_where('companynotifications',array('cn_id'=>$cn_id))->row_array();
    }
        
    /*
     * Get all companynotifications
     */
    function get_all_companynotifications()
    {
        $this->db->order_by('cn_id', 'desc');
        return $this->db->get('companynotifications')->result_array();
    }
        
    /*
     * function to add new companynotification
     */
    function add_companynotification($params)
    {
        $this->db->insert('companynotifications',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update companynotification
     */
    function update_companynotification($cn_id,$params)
    {
        $this->db->where('cn_id',$cn_id);
        return $this->db->update('companynotifications',$params);
    }
    
    /*
     * function to delete companynotification
     */
    function delete_companynotification($cn_id)
    {
        return $this->db->delete('companynotifications',array('cn_id'=>$cn_id));
    }
}
