<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Discussion_question_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get discussion_question by question_id
     */
    function get_discussion_question($question_id)
    {
        return $this->db->get_where('discussion_questions',array('question_id'=>$question_id))->row_array();
    }
        
    /*
     * Get all discussion_questions
     */
    function get_all_discussion_questions()
    {
        $this->db->order_by('question_id', 'desc');
        return $this->db->get('discussion_questions')->result_array();
    }
        
    /*
     * function to add new discussion_question
     */
    function add_discussion_question($params)
    {
        $this->db->insert('discussion_questions',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update discussion_question
     */
    function update_discussion_question($question_id,$params)
    {
        $this->db->where('question_id',$question_id);
        return $this->db->update('discussion_questions',$params);
    }
    
    /*
     * function to delete discussion_question
     */
    function delete_discussion_question($question_id)
    {
        return $this->db->delete('discussion_questions',array('question_id'=>$question_id));
    }
}
