<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Like_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get like by like_id
     */
    function get_like($like_id)
    {
        return $this->db->get_where('likes',array('like_id'=>$like_id))->row_array();
    }
        
    /*
     * Get all likes
     */
    function get_all_likes()
    {
        $this->db->order_by('like_id', 'desc');
        return $this->db->get('likes')->result_array();
    }
        
    /*
     * function to add new like
     */
    function add_like($params)
    {
        $this->db->insert('likes',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update like
     */
    function update_like($like_id,$params)
    {
        $this->db->where('like_id',$like_id);
        return $this->db->update('likes',$params);
    }
    
    /*
     * function to delete like
     */
    function delete_like($like_id)
    {
        return $this->db->delete('likes',array('like_id'=>$like_id));
    }
}
