<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class My_plan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get my_plan by plan_reg_id
     */
    function get_my_plan($plan_reg_id)
    {
        return $this->db->get_where('my_plans',array('plan_reg_id'=>$plan_reg_id))->row_array();
    }
        
    /*
     * Get all my_plans
     */
    function get_all_my_plans()
    {
        $this->db->order_by('plan_reg_id', 'desc');
        return $this->db->get('my_plans')->result_array();
    }
        
    /*
     * function to add new my_plan
     */
    function add_my_plan($params)
    {
        $this->db->insert('my_plans',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update my_plan
     */
    function update_my_plan($plan_reg_id,$params)
    {
        $this->db->where('plan_reg_id',$plan_reg_id);
        return $this->db->update('my_plans',$params);
    }
    
    /*
     * function to delete my_plan
     */
    function delete_my_plan($plan_reg_id)
    {
        return $this->db->delete('my_plans',array('plan_reg_id'=>$plan_reg_id));
    }
}
