<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Plan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get plan by plan_id
     */
    function get_plan($plan_id)
    {
        return $this->db->get_where('plans',array('plan_id'=>$plan_id))->row_array();
    }
        
    /*
     * Get all plans
     */
    function get_all_plans($company_id)
    {
        $this->db->order_by('plan_id', 'desc');
        return $this->db->get_where('plans',array('company_id'=>$company_id))->result_array();
    }
        
    /*
     * function to add new plan
     */
    function add_plan($params)
    {
        $this->db->insert('plans',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update plan
     */
    function update_plan($plan_id,$params)
    {
        $this->db->where('plan_id',$plan_id);
        return $this->db->update('plans',$params);
    }
    
    /*
     * function to delete plan
     */
    function delete_plan($plan_id)
    {
        return $this->db->delete('plans',array('plan_id'=>$plan_id));
    }
}
