<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Review_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get review by review_id
     */
    function get_review($review_id)
    {
        return $this->db->get_where('reviews',array('review_id'=>$review_id))->row_array();
    }
        
    /*
     * Get all reviews
     */
    function get_all_reviews()
    {
        $this->db->order_by('review_id', 'desc');
        return $this->db->get('reviews')->result_array();
    }
        
    /*
     * function to add new review
     */
    function add_review($params)
    {
        $this->db->insert('reviews',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update review
     */
    function update_review($review_id,$params)
    {
        $this->db->where('review_id',$review_id);
        return $this->db->update('reviews',$params);
    }
    
    /*
     * function to delete review
     */
    function delete_review($review_id)
    {
        return $this->db->delete('reviews',array('review_id'=>$review_id));
    }
}
