<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_company_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user_company by user_companies_id
     */
    function get_user_company($user_companies_id)
    {
        return $this->db->get_where('user_companies',array('user_companies_id'=>$user_companies_id))->row_array();
    }
        
    /*
     * Get all user_companies
     */
    function get_all_user_companies()
    {
        $this->db->order_by('user_companies_id', 'desc');
        return $this->db->get('user_companies')->result_array();
    }
        
    /*
     * function to add new user_company
     */
    function add_user_company($params)
    {
        $this->db->insert('user_companies',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update user_company
     */
    function update_user_company($user_companies_id,$params)
    {
        $this->db->where('user_companies_id',$user_companies_id);
        return $this->db->update('user_companies',$params);
    }
    
    /*
     * function to delete user_company
     */
    function delete_user_company($user_companies_id)
    {
        return $this->db->delete('user_companies',array('user_companies_id'=>$user_companies_id));
    }
}
