<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Usernotification_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get usernotification by un_id
     */
    function get_usernotification($un_id)
    {
        return $this->db->get_where('usernotifications',array('un_id'=>$un_id))->row_array();
    }
        
    /*
     * Get all usernotifications
     */
    function get_all_usernotifications()
    {
        $this->db->order_by('un_id', 'desc');
        return $this->db->get('usernotifications')->result_array();
    }
        
    /*
     * function to add new usernotification
     */
    function add_usernotification($params)
    {
        $this->db->insert('usernotifications',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update usernotification
     */
    function update_usernotification($un_id,$params)
    {
        $this->db->where('un_id',$un_id);
        return $this->db->update('usernotifications',$params);
    }
    
    /*
     * function to delete usernotification
     */
    function delete_usernotification($un_id)
    {
        return $this->db->delete('usernotifications',array('un_id'=>$un_id));
    }
}
